worlflow:-
1.Import dataset into MySQL
2.Connect Python ↔ MySQL using mysql.connector
3.Load data into pandas DataFrame
4.Data Cleaning(chack missing value,duplicate then handle it)
5.Data Encoding(lebal/ordinal koi bhi laga ek categorical data=>numerical)
6.Train-Test Split (x,y)
7.Feature Scaling (MinMaxScaler(min=0,max=1), StandardScaler(mean=0,standerdivition=1) accoriding to data )

In [25]:
import numpy as np  
import pandas as pd
import mysql.connector

In [26]:
connect=mysql.connector.connect(
    host="Localhost",
    user="root",
    password="Root@12345",
    database="sqlpython"
)

cursor=connect.cursor()
print("connect mysql")

connect mysql

In [27]:
df=pd.read_sql("select * from tips",connect)
df.head()

C:\Users\krsn\AppData\Local\Temp\ipykernel_5180\2335163566.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("select * from tips",connect)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [29]:
df.duplicated().sum()

np.int64(1)

In [ ]:
from sklearn.preprocessing import LabelEncoder,StandardScaler,MinMaxScaler,OrdinalEncoder,OneHotEncoder

In [31]:
le=LabelEncoder()
for i in df.select_dtypes(include=['object']).columns:
  df[i]=le.fit_transform(df[i])
df.sample(5)

C:\Users\krsn\AppData\Local\Temp\ipykernel_5180\3195269834.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for i in df.select_dtypes(include=['object']).columns:

     total_bill   tip  sex  smoker  day  time  size
40        16.04  2.24    1       0    1     0     3
5         25.29  4.71    1       0    2     0     4
133       12.26  2.00    0       0    3     1     2
128       11.38  2.00    0       0    3     1     2
52        34.81  5.20    0       0    2     0     4

In [32]:
x=df.drop(columns=['total_bill'])
y=df['total_bill']

In [33]:
# oe=OrdinalEncoder(categories=[['Male','Female'],['No','Yes'],['Thur','Fri','Sat','Sun'],['Dinner','Lunch']])
# oe.fit_transform(x)

In [ ]:
# ohe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
# new=ohe.fit_transform(df[['sex','smoker',]])

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
# ss=StandardScaler()
# x_train_ss=ss.fit_transform(x_train)
# x_train_df=pd.DataFrame(x_train_ss,columns=x_train.columns)
# np.round(x_train_df.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean    -0.00    0.00    0.00    0.00    0.00   -0.00
std      1.00    1.00    1.00    1.00    1.00    1.00
min     -1.48   -1.43   -0.83   -1.85   -0.60   -1.63
25%     -0.75   -1.43   -0.83   -0.77   -0.60   -0.60
50%     -0.02    0.70   -0.83    0.32   -0.60   -0.60
75%      0.36    0.70    1.21    0.32    1.66    0.44
max      5.07    0.70    1.21    1.40    1.66    3.55

In [37]:
mm=MinMaxScaler()
x_train_mm=mm.fit_transform(x_train)
x_train_df=pd.DataFrame(x_train_mm,columns=x_train.columns)
np.round(x_train_df.describe(),2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     0.23    0.67    0.41    0.57    0.27    0.31
std      0.15    0.47    0.49    0.31    0.44    0.19
min      0.00    0.00    0.00    0.00    0.00    0.00
25%      0.11    0.00    0.00    0.33    0.00    0.20
50%      0.22    1.00    0.00    0.67    0.00    0.20
75%      0.28    1.00    1.00    0.67    1.00    0.40
max      1.00    1.00    1.00    1.00    1.00    1.00