In [105]:
import numpy as np  
import pandas as pd
import mysql.connector
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [106]:
db=mysql.connector.connect(
    host="Localhost",
    user="root",
    password="Root@12345",
    database="advance_python"
)

cursor=db.cursor()
print("connect mysql")

connect mysql

In [107]:
df=pd.read_sql("select * from insurance",db)
df.sample(5)

C:\Users\krsn\AppData\Local\Temp\ipykernel_10732\2123414343.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("select * from insurance",db)

      age     sex     bmi  children smoker     region      charges
181    18  female  38.280         0     no  southeast   1631.82120
825    64  female  31.825         2     no  northeast  16069.08475
365    49  female  30.780         1     no  northeast   9778.34720
1204   18  female  27.280         3    yes  southeast  18223.45120
696    53  female  32.300         2     no  northeast  29186.48236

In [108]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [109]:
df['region'].value_counts()

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64

In [110]:
le=LabelEncoder()
for i in df.select_dtypes(include=['object']).columns:
  df[i]=le.fit_transform(df[i])
df.sample(5)

C:\Users\krsn\AppData\Local\Temp\ipykernel_10732\3195269834.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for i in df.select_dtypes(include=['object']).columns:

      age  sex     bmi  children  smoker  region      charges
617    49    1  25.600         2       1       3  23306.54700
805    45    0  35.815         0       0       1   7731.85785
491    61    0  25.080         0       0       2  24513.09126
1092   23    1  32.700         3       0       3   3591.48000
654    59    0  35.200         0       0       2  12244.53100

In [111]:
x=df.drop(columns=['charges'])
y=df['charges']

In [112]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [113]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [114]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet,LassoCV,ElasticNetCV,RidgeCV
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error, r2_score

In [115]:
#cv
ridge_cv = RidgeCV(alphas=[0.001, 0.01, 0.1, 1, 10], cv=5)
ridge_cv.fit(x_train, y_train)
print(" alpha  Ridge:", ridge_cv.alpha_)

lasso_cv = LassoCV(alphas=[0.001, 0.01, 0.1, 10], cv=5, random_state=42)
lasso_cv.fit(x_train, y_train)
print("alpha  Lasso:", lasso_cv.alpha_)

elastic_cv = ElasticNetCV(alphas=[0.001, 0.01, 0.1, 1, 10],
                          l1_ratio=[0.1, 0.3, 0.5, 0.9, 1],
                          cv=5,random_state=42)
elastic_cv.fit(x_train, y_train)

print("alpha  ElasticNet:", elastic_cv.alpha_)
print("l1_ratio  ElasticNet:", elastic_cv.l1_ratio_)

 alpha  Ridge: 1.0
alpha  Lasso: 10.0
alpha  ElasticNet: 10.0
l1_ratio  ElasticNet: 1.0

In [116]:
models = {
    "Linear Regression": LinearRegression(),
    "Ridge Regression": Ridge(alpha=0.1),
    "Lasso Regression": Lasso(alpha=10.0),
    "ElasticNet Regression": ElasticNet(alpha=10.0, l1_ratio=0.1)
}

output = {}

for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    
    output[name] = {
        "R2 Score": round(r2_score(y_test, y_pred), 2),
        "MSE": round(mean_squared_error(y_test, y_pred), 2),
        "MAE": round(mean_absolute_error(y_test, y_pred), 2),
        "RMSE": round(np.sqrt(mean_squared_error(y_test, y_pred)), 2)
    }

In [117]:
df_new = pd.DataFrame(output).T
print(df_new)

                       R2 Score           MSE      MAE      RMSE
Linear Regression          0.75  3.472253e+07  3994.93   5892.58
Ridge Regression           0.75  3.472235e+07  3995.10   5892.57
Lasso Regression           0.75  3.471238e+07  3994.46   5891.72
ElasticNet Regression      0.14  1.211401e+08  8554.55  11006.37

# liner regression=> 
- supervised ML algorithm
- used predict numerical value by find  relationship b/w input nad output
- drows best fit straght line

# regulazation =>reduce overfitting method
type:-
1. ridge:-reduce coff. value but does not mkae them 0. (reduce overfitting / corr. feature)
2. lass0:- can reduce some coffi. to 0 and help in feature selection
3. elastic net :- combination og=f both rigde and lasso regulaation. 

alpha=> control penalty strength