## workflow of Machine learning :-
- Data Ingestion --> Data cleaning and preprocessing --> Select best ml model according to data
- --->Model Traning --> Model predictiion -->Model performacne Evaluation.

## Type of ML Model:-
- (1). supervised Ml Model --> In this, we will train our labelled data
- (2). Unsupervised Ml Model --> In this, we will train our unlabelled data




## (1). supervised Ml Model :-  
- if our Target Data is::-
- - (1). numerical --> linearRegression,D.T.Regressor,R.F. Regressor
- - (2). categorical --> LogisticRegression ,D.T. Classifier,R.F. classifire,Naive,SVM,KNN

## (1). Linear Regression Model :-

- Linear Regression:-Linear Regression is a supervised machine learning algorithm used to predict a continuous numerical value.

- Linear Regression tries to fit the best straight line through the data points.

- - The equation is:

Y=mX+b

Where:

Y = Predicted value (Target)
X = Input feature
m = Slope (how much Y changes when X changes)
b = Intercept (starting value)

- # Workflow
Collect Data

      ↓

Train Linear Regression Model

      ↓

Find Best Line

      ↓

Learn Relationship

      ↓
      
Predict New Values

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/insurance - insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb= LabelEncoder()

In [ ]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])

In [ ]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [ ]:
x=df.drop(columns=['charges'])
y=df['charges']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [ ]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=lr.predict(x_test)

In [ ]:
y_pred

array([ 1885.54165174, 11944.32273357, 10455.55488707,  2397.96696161,
        8271.55347048, 11234.41036809,  3376.43169724,  1072.63123623,
       12060.51395933,  9468.23322457, 11494.97066851,  5053.0305502 ,
       30093.5527384 ,  -228.58148206, 12784.84199754, 13402.21956446,
        4179.28948043,  7740.09899682, 29568.66245635,  2738.01455718,
       12343.38521075,  1881.51269934, 34087.95253065, 32103.24119851,
       30445.32061394,  8632.58788645,  2298.01995336, 15417.01187725,
        6168.10928884,  1942.95830544,  9636.84483913,  5642.81556233,
        4058.10854408,  4853.19902886,  9764.94270973,  4755.04190386,
       30007.20570516,  6403.4791383 , 27582.56773006, 14149.40158117,
         151.96770571, 28000.88252814,  7724.4555082 ,  1093.99727743,
       10434.24794603,  7636.92275042, 11467.16787872,  8328.38879353,
       10915.23415866, 13408.79328   ,  6150.60763788, -1131.05313916,
       26163.22877049, 36999.48645124,  6988.24506067, 17480.13399005,
        1018.83694558, 11202.85589973,  1775.35390886, 34195.62805741,
       11482.93499856,   489.95740987,  3859.74367758, 36051.47915417,
       -1428.73834052, 14328.37292632, 14447.33699801,  3547.73959496,
       13086.4043211 , 11047.27999843, 11195.05001964, 16319.16806083,
       10029.69471548,  9522.20376728, 15522.39790841, 12002.45799506,
        4004.69702408,  3510.12174794,  5490.17653227, 13128.9199443 ,
        8771.82281042, 12309.46045053,  9667.79765657, 27287.68697984,
       12790.05452343,  3828.26275901, 38670.29110584, 11019.60083986,
        8452.47984123, 11229.41055335, 11339.4032459 , 14744.9636076 ,
       11255.03748123, 13436.6866804 ,  5675.68835376, 25774.18377058,
        4802.47207367, 10695.16392711,  3083.49609515, 29128.1781461 ,
        6744.14121214,  3621.45701886,  2284.90090761, 16142.63905509,
        7743.99450366,  9909.25632884,  9809.85561134,  5217.94371569,
       15243.60845691, 34129.65579923,  3932.05307004, 11135.43095089,
       24974.58491491, 15196.34870014,  2109.56802097, 10238.04244103,
        8827.26636406,  6118.09284474, 11453.00870576, 28992.60115388,
        6185.07119212,  6796.38004975, 16007.47097303, 16618.20181147,
        8413.48368377, 26675.27315058, 35422.17964258, 11480.17024933,
        7928.5040558 ,  9505.55610531,  8313.45553744,  3299.55807657,
        2939.66896258,  4531.09220084,  8171.97567366,  8385.88030102,
        7196.89330173, 28798.69273278, 34783.89321682,  4004.80792333,
       27471.72298415,  4000.98272662,  6467.74992944, 13471.79662831,
        7640.81825725, 36599.60475814, 11632.338848  , 11176.81793909,
        8132.94575674,   139.36211328,  6128.3827736 ,  7343.67722403,
        4791.42565069, 11272.08677524, 11459.58372532, 15629.94726772,
        6221.72900476, 28022.48030541,  1817.25727984, 11850.04403479,
       17348.8574798 , 14093.51075429,  9135.77746229,  2643.67726663,
        4252.29103098,  9091.64865318, 19165.47389035, 28619.39904963,
       13039.98721697,  3108.76523149, 32669.04229311, 12723.2025417 ,
       33140.28344844, 34726.63313521, 11535.8676401 ,  7199.88544155,
        3024.22410514,  2738.01455718, 11807.82226082,  7517.80179646,
        2755.99762284,   996.35903981, 31500.42047313,  6981.97510029,
        5701.96925175, 27133.30941183,  6975.90000327,  2806.78733149,
        7756.08876538, 35216.05656821,  8145.26232535,  4480.71969408,
        9630.20617573, 27232.90944478,  6088.13270089, 40327.75571182,
       37083.16692232, 13381.78417846, 26961.74999462, 12285.99199376,
       37601.19299442,  7241.19040128,  4044.28958536,  1809.38543828,
       14457.64541495, 13847.63368951,  2545.43395147, 35826.12909961,
       12424.11686557,  8899.08300547,   747.97468776, 30768.7660853 ,
        3869.007392  ,  3833.5970121 , 12437.58188106, 14919.93398073,
       29278.44958711,  -475.84225118,  3336.07577736,  8301.60736115,
       40115.68844976,  8381.46393953, 35473.32544551, 27087.81718701,
       13568.80908294, 29028.31497875, 16893.22465803,  7775.19510378,
       15988.04055919,  7290.41681042, 10608.67726746,  3334.72630606,
        8423.76097226,  1750.4597282 , 32990.56624809, 31881.92819305,
       14441.70241637, 11037.05552582,  1382.84301454,  6137.49001937,
       10799.15221794,  4326.30554377, 10613.54039697,   661.59126724,
       34713.28762089, 32561.54987973, 10371.33933838, 26484.49202386,
       12661.21629752,  2113.0352194 , 10822.99887005,  2800.8592108 ,
        7898.64937714, 10288.02896912, 16725.91611812,  5619.38226062,
       10164.23107528,  -156.85099917, -1979.34595418,  1515.03753962,
       27904.40808058, 33822.00624667, 37719.74320731, -2054.82719361,
       16088.03494606, 36783.48306159, 13147.66223851, 33998.49281923])

In [ ]:
y_train

882      2585.85065
505      6796.86325
798     11848.14100
792      2731.91220
201      8871.15170
           ...
466     13224.69300
299      9249.49520
493     12574.04900
527      9861.02500
1192    13019.16105
Name: charges, Length: 1070, dtype: float64

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7445422986536503

- practies:-

In [ ]:
df=pd.read_csv("/content/tips.csv")
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['day']=lb.fit_transform(df['day'])
df['time']=lb.fit_transform(df['time'])

In [ ]:
df.head()

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3
3       23.68  3.31    1       0    2     0     2
4       24.59  3.61    0       0    2     0     4

In [ ]:
x=df.drop(columns=['tip'])
y=df['tip']

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=90)

In [ ]:
lr.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=lr.predict(x_test)

In [ ]:
y_train

225    2.50
52     5.20
60     3.21
175    3.11
116    5.07
       ...
67     1.00
159    2.00
114    4.00
157    3.75
91     3.50
Name: tip, Length: 195, dtype: float64

In [ ]:
r2_score(y_test,y_pred)

0.3866363484271549

-- 13/05/2026-- --------------------------------------------------------

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler ,LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge,Lasso,ElasticNet
from sklearn.metrics import r2_score,mean_squared_error

In [ ]:
df=pd.read_csv('/content/insurance - insurance.csv')
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [ ]:
lb=LabelEncoder()
df['sex']=lb.fit_transform(df['sex'])
df['smoker']=lb.fit_transform(df['smoker'])
df['region']=lb.fit_transform(df['region'])

df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [ ]:
x=df.drop(columns=['charges'])
y=df['charges']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

## Ridge:-
- -Ridge adds L2 penalty
- - it reduces cofficient value but does not make them exactly zero.

In [ ]:
ridge_model=Ridge(alpha=1.0)
ridge_model.fit(x_train,y_train)

Ridge()

In [ ]:
ridge_pred=ridge_model.predict(x_test)

In [ ]:
ridge_mse=mean_squared_error(y_test,ridge_pred)
ridge_r2=r2_score(y_test,ridge_pred)
print("MSE:",ridge_mse)
print("R2-Score:",ridge_r2)
print("\n Coficients:",ridge_model.coef_)

MSE: 33641818.58882587
R2-Score: 0.7833037457661384

 Coficients: [ 3.61244853e+03 -8.73095622e+00  2.02671768e+03  5.16517239e+02
  9.54798452e+03 -3.01857800e+02]

## Lasso :-  
- lasso adds L1 penalty
- it can make some cofficients exactly zero to performs feature selection.

In [ ]:
lasso_model=Lasso(alpha=0.1)
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.1)

In [ ]:
lasso_pred= lasso_model.predict(x_test)

In [ ]:
lasso_mse=mean_squared_error(y_test,lasso_pred)
lasso_r2=r2_score(y_test,lasso_pred)
print("MSE:",lasso_mse)
print("R2-Score:",lasso_r2)
print("\n cofficients:",lasso_model.coef_)

MSE: 33635473.22337668
R2-Score: 0.7833446180192526

 cofficients: [ 3.61602151e+03 -9.28056722e+00  2.02819649e+03  5.16568126e+02
  9.55703303e+03 -3.02268134e+02]

## ElasticNet combines both:-  
- L1 regularization (Lasso)
- L2 regularization (Ridge)

In [ ]:
elastic_model=ElasticNet(alpha=0.1,l1_ratio=0.5)
elastic_model.fit(x_train,y_train)

ElasticNet(alpha=0.1)

In [ ]:
elastic_pred=elastic_model.predict(x_test)

In [ ]:
elastic_mse=mean_squared_error(y_test,elastic_pred)
elastic_r2=r2_score(y_test,elastic_pred)
print("MSE:",elastic_mse)
print("R2-Score:",elastic_r2)
print("\n cofficients :",elastic_model.coef_)

MSE: 34238439.61428728
R2-Score: 0.7794607447977664

 cofficients : [3430.23775281   22.74438893 1946.4078572   508.36314547 9090.70832049
 -275.8133229 ]

## cross validation

In [ ]:
from sklearn.linear_model import  LassoCV
lasso_cv=LassoCV(
    alphas=[0.001,0.01,0.1,10],
    cv=5,
    random_state=42
)
lasso_cv.fit(x_train,y_train)
print("best Alpha:",lasso_cv.alpha_)

NameError: name 'x_train' is not defined

In [ ]:
from sklearn.linear_model import ElasticNetCV
elastic_cv=ElasticNetCV(
    alphas=[0.001,0.01,0.1,1,10],
    l1_ratio=[0.1,0.3,0.5,0.9,1],
    cv=5,
    random_state=42
)
elastic_cv.fit(x_train,y_train)
print("best Alpha:",elastic_cv.alpha_)
print("best l1_ratio:",elastic_cv.l1_ratio_)

best Alpha: 10.0
best l1_ratio: 1.0