#RandomForestClassifier
 -Random Forest Classifier is a supervised machine learning algorithm used for classification problems.

 #Why Random Forest?

- Decision Tree ki problem:

Decision Tree

     ↓

Can Overfit

=>Ek single tree kabhi-kabhi galat prediction kar sakta hai.

#Random Forest:

Many Decision Trees

        ↓

Majority Voting

        ↓

Final Prediction

=> Isliye Random Forest usually Decision Tree se better perform karta hai.

#Important Parameters
   -  # n_estimators

Number of trees.

RandomForestClassifier(n_estimators=100)

Means:

100 Decision Trees

=> More trees → Better accuracy (usually) but slower training.

#random_state
random_state=42

Same result every time.

#max_depth

Tree ki maximum depth.

max_depth=5

Overfitting control karne ke liye.

#Advantages

✔ High Accuracy

✔ Less Overfitting than Decision Tree

✔ Handles large datasets

✔ Works with missing patterns and noisy data

✔ Feature importance provide karta hai

#Disadvantages

❌ Training slower than one Decision Tree

❌ More memory use karta hai

❌ Harder to interpret

| Decision Tree      | Random Forest           |
| ------------------ | ----------------------- |
| Single Tree        | Many Trees              |
| Fast               | Slower                  |
| Overfitting zyada  | Overfitting kam         |
| Less Accurate      | More Accurate           |
| Easy to Understand | Difficult to Understand |

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Attrition - Attrition.csv")
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['Attrition']=lb.fit_transform(df['Attrition'])
df['BusinessTravel']=lb.fit_transform(df['BusinessTravel'])
df['Department']=lb.fit_transform(df['Department'])
df['EducationField']=lb.fit_transform(df['EducationField'])
df['Gender']=lb.fit_transform(df['Gender'])
df['JobRole']=lb.fit_transform(df['JobRole'])
df['MaritalStatus']=lb.fit_transform(df['MaritalStatus'])
df['Over18']=lb.fit_transform(df['Over18'])
df['OverTime']=lb.fit_transform(df['OverTime'])
df.head(2)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,2,1102,2,1,2,1,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,1,279,1,8,1,1,1,2,...,4,80,1,10,3,3,10,7,1,7

In [ ]:
x=df.drop(columns=['Attrition'])
y=df['Attrition']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
from sklearn.metrics import accuracy_score
y_pred=rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.8775510204081632

In [ ]:
# practies:- class

In [ ]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [ ]:
x=df.drop(columns=["has_covid"])
y=df["has_covid"]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.5

#RandomForestRegression