In [131]:
import numpy as np
import pandas as pd
import mysql.connector

In [132]:
krsn=mysql.connector.connect(
    host="Localhost",
    user='root',
    password='Root@12345',
    database='advance_python'
)
cursor=krsn.cursor
print("chal gya!")

chal gya!

In [133]:
df=pd.read_sql("select * from churn",krsn)
df.head()

C:\Users\krsn\AppData\Local\Temp\ipykernel_8504\3474942384.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("select * from churn",krsn)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [134]:
df=df.drop(columns='Surname')

In [135]:
df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [136]:
from sklearn.preprocessing import LabelEncoder

In [137]:
lb=LabelEncoder()

In [138]:
df['Geography']=lb.fit_transform(df['Geography'])

In [139]:
df['Gender']=lb.fit_transform(df['Gender'])

In [140]:
df.head()

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [141]:
x=df.drop(columns='Exited')
y=df['Exited']

In [142]:
from sklearn.model_selection import train_test_split

In [143]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=34)

In [144]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [145]:
x_train_sc=sc.fit_transform(x_train)
x_train_df=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [146]:
np.round(x_train_df.describe(),2)

,RowNumber,CustomerId,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00,8000.00
mean,-0.00,-0.00,-0.00,0.00,0.00,0.00,0.00,-0.00,-0.00,-0.00,-0.00,0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.74,-1.75,-3.11,-0.90,-1.10,-1.99,-1.73,-1.22,-0.92,-1.54,-1.03,-1.73
25%,-0.86,-0.87,-0.69,-0.90,-1.10,-0.65,-0.69,-1.22,-0.92,-1.54,-1.03,-0.85
50%,0.00,0.01,0.01,-0.90,0.91,-0.17,-0.00,0.33,-0.92,0.65,0.97,0.01
75%,0.87,0.87,0.70,1.51,0.91,0.50,1.03,0.83,0.81,0.65,0.97,0.85
max,1.73,1.72,2.07,1.51,0.91,5.08,1.73,2.80,4.27,0.65,0.97,1.74

practies part 2

In [147]:
df=pd.read_sql("select * from covid",krsn)
df.head()

C:\Users\krsn\AppData\Local\Temp\ipykernel_8504\150089313.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("select * from covid",krsn)

   age  gender  fever cough     city has_covid
0   60    Male    103  Mild  Kolkata        No
1   27    Male    100  Mild    Delhi       Yes
2   42    Male    101  Mild    Delhi        No
3   31  Female     98  Mild  Kolkata        No
4   65  Female    101  Mild   Mumbai        No

In [148]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['has_covid']=lb.fit_transform(df['has_covid'])
df['city']=lb.fit_transform(df['city'])

In [149]:
df.head()

   age  gender  fever  cough  city  has_covid
0   60       1    103      0     2          0
1   27       1    100      0     1          1
2   42       1    101      0     1          0
3   31       0     98      0     2          0
4   65       0    101      0     3          0

In [150]:
x=df.drop(columns='has_covid')
y=df['has_covid']

In [151]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=90)

In [152]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()

In [153]:
x_train_mm=mm.fit_transform(x_train)
x_train_df=pd.DataFrame(x_train_mm,columns=x_train.columns)

In [154]:
np.round(x_train_df.describe(),2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean    0.49    0.36   0.49   0.33   0.48
std     0.32    0.48   0.35   0.47   0.35
min     0.00    0.00   0.00   0.00   0.00
25%     0.19    0.00   0.17   0.00   0.25
50%     0.51    0.00   0.50   0.00   0.67
75%     0.78    1.00   0.83   1.00   0.67
max     1.00    1.00   1.00   1.00   1.00