In [26]:
import numpy as np
import pandas as pd
import mysql.connector

In [27]:
krsn=mysql.connector.connect(
    host="Localhost",
    user='root',
    password='Root@12345',
    database='advance_python'
)
cursor=krsn.cursor
print("chal gya bc")

chal gya bc

In [28]:
df=pd.read_sql("select * from titanic",krsn)

C:\Users\krsn\AppData\Local\Temp\ipykernel_2204\3309545.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("select * from titanic",krsn)

In [29]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,,S

In [30]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [31]:
df=df.drop(columns=['Name','Cabin'])

In [32]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,male,34.5,0,0,330911,7.8292,Q
1,893,1,3,female,47.0,1,0,363272,7.0000,S
2,894,0,2,male,62.0,0,0,240276,9.6875,Q
3,895,0,3,male,27.0,0,0,315154,8.6625,S
4,896,1,3,female,22.0,1,1,3101298,12.2875,S

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
lb=LabelEncoder()
df['Sex']=lb.fit_transform(df['Sex'])

In [35]:
df['Embarked'].value_counts()

Embarked
S    162
C     48
Q     21
Name: count, dtype: int64

In [36]:
df['Embarked']=lb.fit_transform(df['Embarked'])

In [37]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,1,34.5,0,0,330911,7.8292,1
1,893,1,3,0,47.0,1,0,363272,7.0000,2
2,894,0,2,1,62.0,0,0,240276,9.6875,1
3,895,0,3,1,27.0,0,0,315154,8.6625,2
4,896,1,3,0,22.0,1,1,3101298,12.2875,2

In [39]:
x=df.drop(columns='Fare')
y=df['Fare']

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=90)

In [42]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [43]:
x_train_sc=sc.fit_transform(x_train)
x_train_df=pd.DataFrame(x_train_sc,columns=x_train.columns)

In [44]:
np.round(x_train_df.describe(),2)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Embarked
count,184.00,184.00,184.00,184.00,184.00,184.00,184.00,184.00,184.00
mean,-0.00,0.00,0.00,0.00,-0.00,0.00,-0.00,-0.00,-0.00
std,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.69,-0.71,-1.44,-1.40,-2.23,-0.61,-0.41,-0.55,-1.96
25%,-0.89,-0.71,-1.44,-1.40,-0.69,-0.61,-0.41,-0.50,-0.68
50%,0.05,-0.71,-0.25,0.71,-0.26,-0.61,-0.41,-0.04,0.59
75%,0.88,1.40,0.93,0.71,0.53,0.93,-0.41,0.22,0.59
max,1.63,1.40,0.93,0.71,2.52,5.53,6.67,6.35,0.59

In [45]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()
x_train_mm=mm.fit_transform(x_train)
x_train_df2=pd.DataFrame(x_train_mm,columns=x_train.columns)

In [46]:
np.round(x_train_df2.describe(),2)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Embarked
count,184.00,184.00,184.00,184.00,184.00,184.00,184.00,184.00,184.00
mean,0.51,0.34,0.61,0.66,0.47,0.10,0.06,0.08,0.77
std,0.30,0.47,0.42,0.47,0.21,0.16,0.14,0.15,0.39
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.24,0.00,0.00,0.00,0.32,0.00,0.00,0.01,0.50
50%,0.52,0.00,0.50,1.00,0.41,0.00,0.00,0.07,1.00
75%,0.77,1.00,1.00,1.00,0.58,0.25,0.00,0.11,1.00
max,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00